### ISSUE TITLE
url of mac address (oui.txt) has changed?

### ISSUE THREAD

**Issue by Isma399** [pdav/netmagis#138]
Hello,

I've just started to install Netmagis and it seems that the URL of the list of MAcAdress has changed.
I tried http://standards.ieee.org/develop/regauth/oui36/oui36.txt and that worked.

Could anyone validate this URL?

Thank you.

**Comment by pdav** [comment]
This URL is not valid (see http://standards.ieee.org/faqs/regauth.html#21).

You should use http://standards-oui.ieee.org/oui.txt which seems to be the URL-of-today.

We keep this issue open while trying to cope with this mess.
