### ISSUE TITLE
crypt on centos 7

### ISSUE THREAD

**Issue by Isma399** [pdav/netmagis#139]
Hello,

I'm using centos7 to install netmagis.
in etc/netmagis.conf, the command "crypt" was :  openssl passwd -1 %s
I wasn't able to authenticate against postgres.
I changed it for : openssl passwd -apr1 %s (Apache-specific MD5 algorithm).
That works.

**Comment by pdav** [comment]
Crypt configuration parameter is removed in 2.3 release.
