### ISSUE TITLE
LDAP authentication against Active Directory allows empty passwords

### ISSUE THREAD

**Issue by danlii** [pdav/netmagis#173]
An LDAP bind with empty password against an Active Directory gets "translated" to an anonymous bind, like so: 
Authenticated as: 'NT AUTHORITY\ANONYMOUS LOGON'. 
Depending on the LDAP client, this is interpreted as a successful bind with the correct username, and this is the case with the tcllib ldap module. To prevent logins with empty passwords in Netmagis, we would need to prevent empty passwords altogether, at least when the LDAP server is an Active Directory.

**Comment by pdav** [comment]
According to [RFC 4513, section 5.1.2](https://tools.ietf.org/html/rfc4513#section-5.1.2), LDAP authentication falls back to "unauthenticated bind" when given an empty password. This seems to be perfectly legal, albeit absurd.
User authentication needs to be blocked when an empty password is given.

**Comment by pdav** [comment]
Release 2.3.4 is now published.
Thanks for your report.
