### ISSUE TITLE
Option to disconnect

### ISSUE THREAD

**Issue by RomDmz** [pdav/netmagis#60]
I realized that there is no way to disconnect from NetMagis. I think that I think it would be prudent to find a way to add a logout, but i don't know how to do (I'm only a trainee). 

If someone find how to, i think it would be good.
 
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

Je me suis rendu compte qu'il n'existe pas de moyen de se déconnecter de NetMagis. Je pense qu'il serait plus prudent de trouver une solution pour se déloguer  mais je ne trouve pas comment (je ne suis qu'un stagiaire)

Si quelqu'un trouve comment faire je pense que ce serait une bonne chose.

 |--------------------------|
| Romain DUMETZ  |
 |--------------------------|

**Comment by pdav** [comment]
Closed with version 2.3.0
